parameters:
#    ucd_tweet_tweet.example.class: UCDTweet\TweetBundle\Example

services:
#    ucd_tweet_tweet.example:
#        class: %ucd_tweet_tweet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
